"""Email template system for RideCast notifications."""

from typing import Dict, Any


def create_ride_email_html(summary: str, fun_fact: str, user_name: str) -> str:
    """Create formatted HTML email body for ride recommendations."""
    return f"""
    <html>
        <head>
            <style>
                body {{
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    line-height: 1.6;
                    margin: 0;
                    padding: 20px;
                    background-color: #f5f5f5;
                }}
                .container {{
                    max-width: 600px;
                    margin: 0 auto;
                    background-color: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }}
                .header {{
                    text-align: center;
                    border-bottom: 3px solid #e74c3c;
                    padding-bottom: 20px;
                    margin-bottom: 20px;
                }}
                .summary {{
                    background-color: #f8f9fa;
                    padding: 20px;
                    border-left: 4px solid #17a2b8;
                    margin: 20px 0;
                }}
                .fun-fact {{
                    background-color: #fff3cd;
                    border: 1px solid #ffeaa7;
                    border-radius: 5px;
                    padding: 15px;
                    margin: 20px 0;
                }}
                .footer {{
                    text-align: center;
                    margin-top: 30px;
                    color: #666;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🏍️ RideCast for {user_name}</h1>
                </div>
                
                <div class="summary">
                    <h3>🌤️ Weather Summary</h3>
                    <p>{summary}</p>
                </div>
                
                <div class="fun-fact">
                    <h3>🏍️ Motorcycle Tip</h3>
                    <p>{fun_fact}</p>
                </div>
                
                <div class="footer">
                    <p>Stay safe and ride responsibly!</p>
                    <p><em>Generated by RideCast</em></p>
                </div>
            </div>
        </body>
    </html>
    """


def create_fallback_email_html(content: str, user_name: str) -> str:
    """Create simple HTML email for fallback scenarios."""
    return f"""
    <html>
        <head>
            <style>
                body {{
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    line-height: 1.6;
                    margin: 0;
                    padding: 20px;
                    background-color: #f5f5f5;
                }}
                .container {{
                    max-width: 600px;
                    margin: 0 auto;
                    background-color: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }}
                .header {{
                    text-align: center;
                    border-bottom: 3px solid #e74c3c;
                    padding-bottom: 20px;
                    margin-bottom: 20px;
                }}
                .content {{
                    white-space: pre-wrap;
                    background-color: #f8f9fa;
                    padding: 20px;
                    border-radius: 5px;
                }}
                .footer {{
                    text-align: center;
                    margin-top: 30px;
                    color: #666;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🏍️ RideCast for {user_name}</h1>
                </div>
                
                <div class="content">
                    {content}
                </div>
                
                <div class="footer">
                    <p>Stay safe and ride responsibly!</p>
                    <p><em>Generated by RideCast</em></p>
                </div>
            </div>
        </body>
    </html>
    """


def create_subject_line(should_ride: bool, user_name: str, temperature: str = "N/A") -> str:
    """Create email subject line based on ride recommendation."""
    ride_emoji = "✅" if should_ride else "❌"
    temp_str = f" - {temperature}°F" if temperature != "N/A" else ""
    return f"🏍️ {ride_emoji} RideCast for {user_name}{temp_str}"