# fly.toml file generated for RideCast FastAPI app
app = "ridecast"         # <-- change this to your app name on Fly.io
primary_region = "ewr"       # <-- choose a region near you/users (iad = US East, fra = Frankfurt, etc.)

[build]
  # If you use a Dockerfile, comment this out
  image = "python:3.11-slim"

[env]
  # Set environment variables for your app
  PYTHONUNBUFFERED = "true"
  PORT = "8080"

[deploy]
  # Run migrations or init scripts here if you need them
  # release_command = "python migrate.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
