app = "ridecast-api"          # change if this name already exists
primary_region = "ewr"        # or your closest region

[env]
  PYTHONUNBUFFERED = "true"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false   # set true if you want scale-to-zero
  min_machines_running = 1
